# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duck < Formula
  desc "P2P Chat"
  homepage "https://github.com/dripverse/duck"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DripVerse/duck/releases/download/v1.0.0/duck_Darwin_arm64.tar.gz"
      sha256 "6953e92030aa5c80e22a150e912bdbba36671b8e774b5f812b682e3214d61e4b"

      def install
        bin.install "duck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DripVerse/duck/releases/download/v1.0.0/duck_Darwin_x86_64.tar.gz"
      sha256 "99e6121fa60a2ad31dd4ea35379241620d9e5c80299edf1df9d094ab18def6f5"

      def install
        bin.install "duck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DripVerse/duck/releases/download/v1.0.0/duck_Linux_arm64.tar.gz"
      sha256 "ef8547a23f41e6cdd63b20116c6dfe43510eb28b18430fcd13dbb3b7a15493c5"

      def install
        bin.install "duck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DripVerse/duck/releases/download/v1.0.0/duck_Linux_x86_64.tar.gz"
      sha256 "b7a5e5edcd9d85cf58df13a16624baf3db5e0e09676886d971acdf2ecb1c05bf"

      def install
        bin.install "duck"
      end
    end
  end
end
